# Generated by Django 3.0.5 on 2021-06-09 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210609_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10, 'Оценка не должна превышать 10')], verbose_name='Оценка'),
        ),
    ]
